from django.db import models
from django.utils import timezone

# Create your models here.
class datosAcalcular (models.Model):
    idOcupacionMq = models.IntegerField('idOcupacionMq')
    cortesXminuto = models.DecimalField('cortesXminuto', max_digits=10, decimal_places=4)
    tiempoCicloXpza = models.DecimalField('tiempoCicloXpza', max_digits=10, decimal_places=4)
    pzaRequeridas = models.DecimalField('pzaRequeridas', max_digits=10, decimal_places=4)
    golpesXminutos = models.DecimalField('golpesXminutos', max_digits=10, decimal_places=4)
    requeriAnualAutilizar = models.DecimalField('requeriAnualAutilizar', max_digits=10, decimal_places=4)
    longTrabajoBanda = models.DecimalField('longTrabajoBanda', max_digits=10, decimal_places=4)
    longTotalBanda = models.DecimalField('longTotalBanda', max_digits=10, decimal_places=4)
    longEfectivoBanda = models.DecimalField('longEfectivoBanda', max_digits=10, decimal_places=4)
    velocidadBanda = models.DecimalField('velocidadBanda', max_digits=10, decimal_places=4)
    longDePza = models.DecimalField('longDePza', max_digits=10, decimal_places=4)
    espacioEntrePza = models.DecimalField('espacioEntrePza', max_digits=10, decimal_places=4)
    semanasAlaborar = models.DecimalField('semanasAlaborar', max_digits=10, decimal_places=4)
    diasAlaborarSemana = models.DecimalField('diasAlaborarSemana', max_digits=10, decimal_places=4)
    horasDelTurno = models.DecimalField('horasDelTurno', max_digits=10, decimal_places=4)
    turnosAlDia = models.DecimalField('turnosAlDia', max_digits=10, decimal_places=4)
    tiempoSetUp = models.DecimalField('tiempoSetUp', max_digits=10, decimal_places=4)
    cambioHerramental = models.DecimalField('cambioHerramental', max_digits=10, decimal_places=4)
    numDeCambiosHerra = models.DecimalField('numDeCambiosHerra', max_digits=10, decimal_places=4)
    paradasProgramadas = models.DecimalField('paradasProgramadas', max_digits=10, decimal_places=4)
    demorasInevitables = models.DecimalField('demorasInevitables', max_digits=10, decimal_places=4)
    cavidades = models.DecimalField('cavidades', max_digits=10, decimal_places=4)
    turnoInicial = models.DecimalField('turnoInicial', max_digits=10, decimal_places=4)
    turnoConsecutivo = models.DecimalField('turnoConsecutivo', max_digits=10, decimal_places=4)
    numLadosAfluxear = models.DecimalField('numLadosAfluxear', max_digits=10, decimal_places=4)
    cantidadDummys = models.DecimalField('cantidadDummys', max_digits=10, decimal_places=4)
    longitudDummy = models.DecimalField('longitudDummy', max_digits=10, decimal_places=4)
    longitudEntreDummys = models.DecimalField('longitudEntreDummys', max_digits=10, decimal_places=4)
    longitudJig = models.DecimalField('longitudJig', max_digits=10, decimal_places=4)
    longitudEntreJigs = models.DecimalField('longitudEntreJigs', max_digits=10, decimal_places=4)
    filasDummysSimultaneas = models.DecimalField('filasDummysSimultaneas', max_digits=10, decimal_places=4)
    filasJigsSimultaneas = models.DecimalField('filasJigsSimultaneas', max_digits=10, decimal_places=4)
    numCambiosReceta = models.DecimalField('numCambiosReceta', max_digits=10, decimal_places=4)
    scrapLiberado = models.DecimalField('scrapLiberado', max_digits=10, decimal_places=4)
    observaciones = models.CharField('observaciones', max_length=255)
    estatus = models.CharField('estatus', max_length=255)
    created_at = models.DateTimeField(auto_now_add=True) 
    updated_at = models.DateTimeField(auto_now=True)    

    def save(self, *args, **kwargs):
        self.updated_at = timezone.now()
        super().save(*args, **kwargs)