# Generated by Django 5.0.4 on 2024-04-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numDepartamento', models.IntegerField(verbose_name='numDepartamento')),
                ('codInternoMq', models.CharField(max_length=255, verbose_name='codInternoMq')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('codInternoProceso', models.CharField(max_length=255, verbose_name='codInternoProceso')),
                ('funcionMaquina', models.CharField(max_length=255, verbose_name='funcionMaquina')),
                ('planta', models.CharField(max_length=255, verbose_name='planta')),
                ('estatus', models.BooleanField(verbose_name='estatus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
