# Generated by Django 5.0.4 on 2024-04-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numParte', models.CharField(max_length=255, verbose_name='numParte')),
                ('descripcion', models.CharField(max_length=255, verbose_name='descripcion')),
                ('tipo', models.CharField(max_length=255, verbose_name='tipo')),
                ('idCliente', models.IntegerField(verbose_name='idCliente')),
                ('funcionMaquina', models.CharField(max_length=255, verbose_name='funcionMaquina')),
                ('estatus', models.BooleanField(verbose_name='estatus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
