# Generated by Django 5.0.4 on 2024-04-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parte',
            name='idCliente',
        ),
        migrations.AddField(
            model_name='parte',
            name='cliente',
            field=models.CharField(default='1', max_length=255, verbose_name='cliente'),
            preserve_default=False,
        ),
    ]
