# Generated by Django 5.0.4 on 2024-05-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parte', '0002_remove_parte_idcliente_parte_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='parte',
            name='codMaqRealiza',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='codMaqRealiza'),
        ),
    ]
