"""
Django settings for backCapacidadMq project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_wf%&axoa+2n&17#*l-#dy5ao^wl&xy_92=l2n5&@&3i-z(krt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #para que permita las conexiones
    'corsheaders', # Agregamos corsheaders
    'rest_framework', # Agregamos rest_framework
    #agregado
    'planta.apps.PlantaConfig',
    'departamento.apps.DepartamentoConfig',
    'parte.apps.ParteConfig',
    'cliente.apps.ClienteConfig',
    'maquina.apps.MaquinaConfig',
    'usuario.apps.UsuarioConfig',
    'ocupacionMq.apps.OcupacionmqConfig',
    'datosAcalcular.apps.DatosacalcularConfig',
    'resultadoCalculo.apps.ResultadocalculoConfig'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Agregamos el middleware de corsheaders
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backCapacidadMq.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backCapacidadMq.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

#DATABASES = {
    #'default': {
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': BASE_DIR / 'db.sqlite3',
    #}
#}
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'capacidadMq',
        'USER': 'sa',
        'PASSWORD': '12345ct',
        'HOST': 'P2TICPC09\SQLEXPRESS',
        'PORT': '',
        'OPTIONS':{
            'driver': 'ODBC Driver 17 for SQL Server'
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#CORS_ORIGIN_ALLOW_ALL = True  # Habilita el acceso CORS desde cualquier origen 
CORS_ALLOW_ALL_HEADERS = True  # Permitir todos los encabezados en las solicitudes CORS

CORS_ALLOWED_ORIGINS = [ #habilita el acceso CORS desde la direccion indicada
    'http://localhost:4200',
]