# Generated by Django 5.0.4 on 2024-05-08 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocupacionMq', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocupacionmq',
            old_name='idMaquina',
            new_name='codInternoMq',
        ),
        migrations.RenameField(
            model_name='ocupacionmq',
            old_name='idParte',
            new_name='numParte',
        ),
    ]
