# Generated by Django 5.0.4 on 2024-05-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocupacionMq', '0003_alter_ocupacionmq_codinternomq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocupacionmq',
            name='funcion',
            field=models.CharField(default='TROQUELAR', max_length=255, verbose_name='funcion'),
            preserve_default=False,
        ),
    ]
