# Generated by Django 5.0.4 on 2024-04-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255, verbose_name='numero')),
                ('nombre', models.CharField(max_length=255, verbose_name='numero')),
                ('encargado', models.CharField(max_length=255, verbose_name='encargado')),
                ('tipo', models.CharField(max_length=255, verbose_name='tipo')),
                ('estatus', models.BooleanField(verbose_name='estatus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
