# Generated by Django 5.0.4 on 2024-04-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='numero',
            field=models.IntegerField(verbose_name='numero'),
        ),
    ]
