# Generated by Django 5.0.4 on 2024-04-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido')),
                ('user', models.CharField(max_length=255, verbose_name='user')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
                ('departamento', models.CharField(max_length=255, verbose_name='departamento')),
                ('estatus', models.BooleanField(verbose_name='estatus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
