# Generated by Django 5.0.4 on 2024-05-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resultadoCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDatosAcalcular', models.IntegerField(verbose_name='idDatosAcalcular')),
                ('proyectadoOcupAnual', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='proyectadoOcupAnual')),
                ('horaSemanaTurno', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='horaSemanaTurno')),
                ('ensamblesXminuto', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='ensamblesXminuto')),
                ('ensamblesXhora', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='ensamblesXhora')),
                ('requerimientoDiario', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='requerimientoDiario')),
                ('requerimientoSem', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='requerimientoSem')),
                ('pzaTeoricasXprimerTurno', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='pzaTeoricasXprimerTurno')),
                ('pzaTeoricasXsegundoTurno', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='pzaTeoricasXsegundoTurno')),
                ('numTurnosRequeridos', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='numTurnosRequeridos')),
                ('pzaProdEnTurnos', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='pzaProdEnTurnos')),
                ('tiempDispoXturno', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='tiempDispoXturno')),
                ('hrsNcesRequeDiario', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='hrsNcesRequeDiario')),
                ('tiempoEfecDiario', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='tiempoEfecDiario')),
                ('ensamReqXdia', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='ensamReqXdia')),
                ('ensamXdiaMasScrap', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='ensamXdiaMasScrap')),
                ('timeCicloXgolpe', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='timeCicloXgolpe')),
                ('hrsEfectivasXturno', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='hrsEfectivasXturno')),
                ('timeMuertoPrimeraColum', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='timeMuertoPrimeraColum')),
                ('tiempoCiclo', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='tiempoCiclo')),
                ('pzaXhora', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='pzaXhora')),
                ('hrsXdiaRequeriSemanal', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='hrsXdiaRequeriSemanal')),
                ('pzaXturno', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='pzaXturno')),
                ('longTotalJigDummy', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='longTotalJigDummy')),
                ('longTotalJigProducto', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='longTotalJigProducto')),
                ('numColDummys', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='numColDummys')),
                ('numColJigProducto', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='numColJigProducto')),
                ('tiempDisponibleHornoAlDia', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='tiempDisponibleHornoAlDia')),
                ('horneadoXpzaPrimerDummy', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='horneadoXpzaPrimerDummy')),
                ('horneadoXpzaRestoDummys', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='horneadoXpzaRestoDummys')),
                ('horneadoXpzaProducto', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='horneadoXpzaProducto')),
                ('tiempRecorriPrimerDummy', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='tiempRecorriPrimerDummy')),
                ('tiempRecorriRestoDummys', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='tiempRecorriRestoDummys')),
                ('tiempRecorridoProducto', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='tiempRecorridoProducto')),
                ('ocupacionPrimerDummy', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='ocupacionPrimerDummy')),
                ('ocupacionRestoDummys', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='ocupacionRestoDummys')),
                ('ocupacionProducto', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='ocupacionProducto')),
                ('estatus', models.CharField(max_length=255, verbose_name='estatus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
