# Generated by Django 5.0.4 on 2024-05-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultadoCalculo', '0002_alter_resultadocalculo_ensamreqxdia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadocalculo',
            name='proyectadoOcupAnual',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='proyectadoOcupAnual'),
        ),
    ]
