# Generated by Django 5.0.4 on 2024-05-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datosAcalcular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idOcupacionMq', models.IntegerField(verbose_name='idOcupacionMq')),
                ('cortesXminuto', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='cortesXminuto')),
                ('tiempoCicloXpza', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='tiempoCicloXpza')),
                ('pzaRequeridas', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='pzaRequeridas')),
                ('golpesXminutos', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='golpesXminutos')),
                ('requeriAnualAutilizar', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='requeriAnualAutilizar')),
                ('longTrabajoBanda', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='longTrabajoBanda')),
                ('longTotalBanda', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='longTotalBanda')),
                ('longEfectivoBanda', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='longEfectivoBanda')),
                ('velocidadBanda', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='velocidadBanda')),
                ('longDePza', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='longDePza')),
                ('espacioEntrePza', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='espacioEntrePza')),
                ('semanasAlaborar', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='semanasAlaborar')),
                ('diasAlaborarSemana', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='diasAlaborarSemana')),
                ('horasDelTurno', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='horasDelTurno')),
                ('turnosAlDia', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='turnosAlDia')),
                ('tiempoSetUp', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='tiempoSetUp')),
                ('cambioHerramental', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='cambioHerramental')),
                ('numDeCambiosHerra', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='numDeCambiosHerra')),
                ('paradasProgramadas', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='paradasProgramadas')),
                ('demorasInevitables', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='demorasInevitables')),
                ('cavidades', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='cavidades')),
                ('turnoInicial', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='turnoInicial')),
                ('turnoConsecutivo', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='turnoConsecutivo')),
                ('numLadosAfluxear', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='numLadosAfluxear')),
                ('cantidadDummys', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='cantidadDummys')),
                ('longitudDummy', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='longitudDummy')),
                ('longitudEntreDummys', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='longitudEntreDummys')),
                ('longitudJig', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='longitudJig')),
                ('longitudEntreJigs', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='longitudEntreJigs')),
                ('filasDummysSimultaneas', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='filasDummysSimultaneas')),
                ('filasJigsSimultaneas', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='filasJigsSimultaneas')),
                ('numCambiosReceta', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='numCambiosReceta')),
                ('scrapLiberado', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='scrapLiberado')),
                ('observaciones', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='observaciones')),
                ('estatus', models.CharField(max_length=255, verbose_name='estatus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
