# Generated by Django 5.0.4 on 2024-05-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosAcalcular', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosacalcular',
            name='observaciones',
            field=models.CharField(max_length=255, verbose_name='observaciones'),
        ),
    ]
