# Generated by Django 5.0.4 on 2024-05-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosAcalcular', '0002_alter_datosacalcular_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosacalcular',
            name='scrapLiberado',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='scrapLiberado'),
        ),
    ]
